version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: goread_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GOREAD_BD
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - goread_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      start_period: 10s
      retries: 10

  app:
    build: .
    container_name: tfg_daw_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/GOREAD_BD?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    networks:
      - goread_network
    restart: on-failure

networks:
  goread_network:
    driver: bridge

volumes:
  mysql_data: {}
